<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>CutMaker</AssemblyName>
    <RootNamespace>CutMaker.App</RootNamespace>
    <Version>0.7.1</Version>
    <Description>CutMaker lightweight video and audio editor</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CutMaker.Core\CutMaker.Core.csproj" />
  </ItemGroup>
</Project>
